"""add_created_at_to_products

Revision ID: bf588680c386
Revises: 2337d32005dc
Create Date: 2026-02-10 11:19:51.984426

"""
from typing import Sequence, Union
from datetime import datetime
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf588680c386'
down_revision: Union[str, Sequence[str], None] = '2337d32005dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Сначала добавляем колонки как NULLABLE
    op.add_column('products', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))

    # 2. Заполняем существующие записи
    op.execute(
        "UPDATE products SET created_at = NOW(), updated_at = NOW()"
    )
    
    # 3. Меняем на NOT NULL
    op.alter_column('products', 'created_at', nullable=False, server_default=sa.text('now()'))
    op.alter_column('products', 'updated_at', nullable=False, server_default=sa.text('now()'))
    
    op.alter_column('reviews', 'comment',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'comment',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'created_at')
    # ### end Alembic commands ###
