"""Create Search Vector

Revision ID: fc00b3a6790d
Revises: bf588680c386
Create Date: 2026-02-12 11:53:30.823557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc00b3a6790d'
down_revision: Union[str, Sequence[str], None] = 'bf588680c386'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("\n                setweight(to_tsvector('english', coalesce(name, '')), 'A')\n                || setweight(to_tsvector('russian', coalesce(name, '')), 'A')\n                || setweight(to_tsvector('english', coalesce(description, '')), 'B')\n                || setweight(to_tsvector('russian', coalesce(description, '')), 'B')\n            ", persisted=True), nullable=False))
    op.create_index('ix_products_tsv_gin', 'products', ['tsv'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_tsv_gin', table_name='products', postgresql_using='gin')
    op.drop_column('products', 'tsv')
    # ### end Alembic commands ###
